const A = '/assets';

export const assets = {
  background: `${A}/background.png`,
  cardBg: `${A}/card-bg.png`,
  paperclip: `${A}/paperclip.png`,
  photo: `${A}/photo.png`,
  arrow: `${A}/arrow.svg`,
  underline: `${A}/underline.svg`,
  sun: `${A}/sun.svg`,
  cloud1: `${A}/cloud1.svg`,
  cloud2: `${A}/cloud2.svg`,
  cloud3: `${A}/cloud3.svg`,
  flowerRed: `${A}/flower-red.svg`,
  flowerPink: `${A}/flower-pink.svg`,
  star1: `${A}/star1.svg`,
  star2: `${A}/star2.svg`,
  star3: `${A}/star3.svg`,
  stickerBg: `${A}/sticker-bg.png`,
  stickerTexture: `${A}/sticker-texture.png`,
  tape: `${A}/tape.png`,
  colorBlue: `${A}/color-blue.svg`,
  colorRed: `${A}/color-red.svg`,
  colorYellow: `${A}/color-yellow.svg`,
  colorPink: `${A}/color-pink.svg`,
  colorGreen: `${A}/color-green.svg`,
  eraser: `${A}/eraser.svg`,
  trashBody: `${A}/trash-body.svg`,
  trashLid: `${A}/trash-lid.svg`,
  iconLinkedin: `${A}/icon-linkedin.svg`,
  iconTelegram: `${A}/icon-telegram.svg`,
  iconMail: `${A}/icon-mail.svg`,
  palitra: `${A}/palitra.png`,
  palitraOverlay: `${A}/palitra-overlay.png`,
  paletteCheck: `${A}/palette-check.svg`,
  footerTelegram: `${A}/footer-telegram.svg`,
  footerMail: `${A}/footer-mail.svg`,
  footerLinkedin: `${A}/footer-linkedin.svg`,
  arrowUx: `${A}/arrow-ux.svg`,
  arrowUi: `${A}/arrow-ui.svg`,
  arrowPm: `${A}/arrow-pm.svg`,
  caseTBank: {
    arrowDown: `${A}/cases/t-bank/arrow-down.svg`,
    arrowUp: `${A}/cases/t-bank/arrow-up.svg`,
    arrowLeft: `${A}/cases/t-bank/arrow-left.svg`,
    heroShowcase: `${A}/cases/t-bank/hero-showcase.png`,
    heroCover: `${A}/cases/t-bank/hero-cover.png`,
    usabilityCollage: `${A}/cases/t-bank/usability-collage.png`,
    mockupsBeforeResearch: `${A}/cases/t-bank/robot-delivery-mockups-before-research.pdf`,
    phoneBezel: `${A}/cases/t-bank/phone-bezel.png`,
    phoneBezelOverlay: `${A}/cases/t-bank/phone-bezel-overlay.png`,
    phoneFrame: `${A}/cases/t-bank/phone-frame.png`,
    phoneScreen1: `${A}/cases/t-bank/phone-screen-1.png`,
    phoneScreen2: `${A}/cases/t-bank/phone-screen-2.png`,
    phoneScreen3: `${A}/cases/t-bank/phone-screen-3.png`,
    robot: `${A}/cases/t-bank/robot.png`,
    starGlow1: `${A}/cases/t-bank/star-glow-1.svg`,
    starGlow2: `${A}/cases/t-bank/star-glow-2.svg`,
    doodleShield: `${A}/cases/t-bank/doodle-shield.svg`,
    doodleHeart: `${A}/cases/t-bank/doodle-heart.svg`,
    doodleSmile: `${A}/cases/t-bank/doodle-smile.svg`,
    flowScreens: `${A}/cases/t-bank/flow-screens.png`,
    robotYandex: `${A}/cases/t-bank/robot-yandex.png`,
    robotSensors1: `${A}/cases/t-bank/robot-sensors-1.png`,
    robotSensors2: `${A}/cases/t-bank/robot-sensors-2.png`,
    designDeliveryChoice: `${A}/cases/t-bank/design-delivery-choice.png`,
    designTracking: `${A}/cases/t-bank/design-tracking.png`,
    designQr: `${A}/cases/t-bank/design-qr.png`,
    designSms: `${A}/cases/t-bank/design-sms.png`,
    designRobotInfo: `${A}/cases/t-bank/design-robot-info.png`,
    principles: `${A}/cases/t-bank/principles.png`,
    benchmarkYandexLavka: `${A}/cases/t-bank/benchmark-yandex-lavka.png`,
    benchmarkStarship: `${A}/cases/t-bank/benchmark-starship.png`,
    benchmarkOzon: `${A}/cases/t-bank/benchmark-ozon.png`,
    benchmarkRaiffeisen: `${A}/cases/t-bank/benchmark-raiffeisen.png`,
    benchmarkAlfa: `${A}/cases/t-bank/benchmark-alfa.png`,
    activationScreen: `${A}/cases/t-bank/activation-screen.png`,
    protoDeliveryChoiceOnboarding: `${A}/cases/t-bank/prototype/delivery-choice-onboarding.mp4`,
    protoOformlenie: `${A}/cases/t-bank/prototype/oformlenie.mp4`,
    protoCalendarEvent: `${A}/cases/t-bank/prototype/calendar-event.mp4`,
    protoTrackingFromHome: `${A}/cases/t-bank/prototype/tracking-from-home.mp4`,
    protoTrackingFromLock: `${A}/cases/t-bank/prototype/tracking-from-lock.mp4`,
    protoWaitingFromHome: `${A}/cases/t-bank/prototype/waiting-from-home.mp4`,
    protoWaitingFromLock: `${A}/cases/t-bank/prototype/waiting-from-lock.mp4`,
    protoVerification: `${A}/cases/t-bank/prototype/verification.mp4`,
    protoOpenError: `${A}/cases/t-bank/prototype/open-error.mp4`,
    protoReviewPositive: `${A}/cases/t-bank/prototype/review-positive.mp4`,
    protoReviewNegative: `${A}/cases/t-bank/prototype/review-negative.mp4`,
  },
} as const;

export const paletteColors = [
  { id: 'blue', hex: '#3969f9', asset: assets.colorBlue },
  { id: 'red', hex: '#f94b4b', asset: assets.colorRed },
  { id: 'yellow', hex: '#ffda33', asset: assets.colorYellow },
  { id: 'pink', hex: '#ffb5e7', asset: assets.colorPink },
  { id: 'green', hex: '#69b578', asset: assets.colorGreen },
] as const;
